version: '3'

services:
  web:
    build: .
    command: python testSite/manage.py runserver
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    environment:
      - DEBUG= True
      - SECRET_KEY= random-secret-key
      - DATABASE_URL= mariadb://username:password@db:3306/databasename
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: databasename
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"  # Map container port 3306 to host port 3306
