version: '3'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_DATABASE=testSite
      - MYSQL_USER=root
      - MYSQL_PASSWORD=some_password
      - MYSQL_ROOT_PASSWORD=some_password
      - MYSQL_HOST=db
    volumes:
      - /tmp/app/mysqld:/var/run/mysqld
      - ./db:/var/lib/mysql
  web:
    build: .
    command: python testSite/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=some_secret_key
      - DEBUG='True'
      - DATABASE_URL='mysql://root:some_password@db:3306/testSite'
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db
