version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - dbnet
    environment:
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_PASSWORD=mariadb
    expose:
      - 3306
  web:
    build:
      context: testSite
      dockerfile: Dockerfile
    restart:
        always
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    environment:
      - DEBUG=True
      - SECRET_KEY=random-secret-key
      - DB_NAME=mariadb
      - DB_USER=mariadb
      - DB_PASSWORD=mariadb
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - dbnet

volumes:
    db_data:

networks:
  dbnet:
