version: '3'

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3308:3306"
  web:
    build: .
    command: python testSite/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=some_secret_key
      - DEBUG='True'
      - DATABASE_URL='mysql://mariadb:mariadb@mariadb:3306/mariadb'
    volumes:
      - .:/app
      - /tmp/app/mysqld:/run/mysqld
    depends_on:
      - db
