apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: testsite
spec:
  ports:
    - port: 6379
  selector:
    app: testsite
    tier: redis
  clusterIP: None
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  labels:
    app: testsite
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testsite-redis
  labels:
    app: testsite
spec:
  selector:
    matchLabels:
      app: testsite
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: testsite
        tier: redis
    spec:
      containers:
      - image: redis:latest
        name: mysql
        command: ["redis-server"]
        args: ["--requirepass", "password"]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /var/lib/redis
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim