version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    environment:
      - DEBUG=True
      - SECRET_KEY=random-secret-key
      - DATABASE_URL=mysql://mariadb:mariadb@db:3306/mariadb
    depends_on:
      - db

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3308:3306"
