version: '3'

services:
  mariadb:
    image: bitnami/mariadb-galera:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_DATABASE=mariadb
      - MARIADB_USER=mariadb
      - MARIADB_PASSWORD=mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
        - webnet
#    ports:
#      - "3306:3306"
  web:
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    environment:
      - DEBUG=True
      - SECRET_KEY=random-secret-key
      - DATABASE_URL=mysql://mariadb:mariadb@mariadb:3306/mariadb
    depends_on:
      - mariadb
    networks:
      - webnet


networks:
    webnet: