version: '3'

services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build:
        context: .
        dockerfile: Dockerfile
    entrypoint: ["./wait.sh"]
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    environment:
      - DEBUG=True
      - SECRET_KEY=random-secret-key
      - DATABASE_URL=mysql://mariadb:mariadb@localhost:3306/mariadb
    depends_on:
      - db
    restart: on-failure

